language: ruby
rvm:
  # SLES12
  - 2.1
  # SLES15
  - 2.5.0
  - 2.5
  # Factory/Tumbleweed
  - 2.6
  - 2.7
before_install:
  - gem install bundler -v 1.17.3
  - bundle
script: bundle exec rspec spec/*
